import Head from 'next/head'
import styles from '../styles/Home.module.css'
import truncateEthAddress from 'truncate-eth-address'

import { useState } from 'react'
import { ethers } from 'ethers'

export default function Home() {

  const [account, setAccount] = useState(null)
  const NETWORK_ID = 80001
  const HEX_NETWORK_ID = "0x13881"
  
  async function connect(){
    if(window.ethereum){
      const provider = new ethers.providers.Web3Provider(window.ethereum);
        await provider.send("eth_requestAccounts");
      if(parseInt(window.ethereum.networkVersion) !== NETWORK_ID){
        try {
          await ethereum.request({
            method: 'wallet_switchEthereumChain',
            params: [{ chainId: HEX_NETWORK_ID }],
          });
        } catch (switchError) {
          if (switchError.code === 4902) {
            try {
              await ethereum.request({
                method: 'wallet_addEthereumChain',
                params: [
                  {
                    chainId: HEX_NETWORK_ID,
                    chainName: 'Mumbai',
                    nativeCurrency: {
                      name: 'MATIC',
                      symbol: 'MATIC',
                      decimals: 18
                    },
                    rpcUrls: ['https://rpc-mumbai.matic.today'],
                  },
                ],
              });
            } catch (addError) {
              // handle "add" error
            }
          }
        }
      }
      let acc = await provider.listAccounts(0);
      acc = acc[0]
      acc = truncateEthAddress(acc)
      setAccount(acc)
    }
    else{
      setAccount("Install Metamask")
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Web3 + Fleek test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to web3 + Fleek dApp
        </h1>

        <p className={styles.description}>
          Get started connecting Metamask
        </p>

        <div className={styles.grid}>
          <a style={{cursor : "pointer"}} onClick={connect} className={styles.card}>
            <h2>Connect your wallet&rarr;</h2>
            {
              !account && (
                <center>
                  <div>
                    <p>🦊</p>
                  </div>
                </center>
              )
            }
            {
              account && <center><p>✅ {account} ✅</p></center>
            }
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://fleek.co/"
          target="_blank"
        >
          Powered by fleek
        </a>
        <a
          href="https://github.com/ivanmmurcia/web3-fleek"
          target="_blank"
        >
          Made by ivanmmurcia
        </a>
      </footer>
    </div>
  )
}
